name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Read release information
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: release_configuration
        with:
          config: ${{ github.workspace }}/version.yaml
      - name: Get next version
        id: next_version
        uses: thenativeweb/get-next-version@main
        with:
            prefix: 'v' # optional, defaults to ''
