name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Run Tests 
        uses: habetuz/TinfInfoUtils/.github/workflows/test.yml@main
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get next version
        id: next_version
        uses: thenativeweb/get-next-version@main
        with:
            prefix: 'v'
      - name: Show the next version
        run: |
          echo ${{ steps.next_version.outputs.version }}
          echo ${{ steps.next_version.outputs.hasNextVersion }}
      - name: Zip source
        uses: vimtor/action-zip@v1.2
        with:
          files: src/main/java/
          dest: release.zip
      - name: Create Release
        uses: ncipollo/release-action@v1
        if: ${{ steps.next_version.outputs.hasNextVersion }}
        with:
          artifacts: "release.zip"
          bodyFile: "release.md"
          tag: ${{ steps.next_version.outputs.version }}
