name: Run tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  Unit-Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: Run tests
      run: mvn test -B
    
